name: Release

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm 8
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: pnpm i

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set version from publishedPackages
        id: setVersion
        if: steps.changesets.outputs.published == 'true'
        env:
          PACKAGE_VERSION: ${{ steps.changesets.outputs.publishedPackages }}
        run: echo "PACKAGE_VERSION=$(echo $PACKAGE_VERSION | jq -r '.[0].version')" >> $GITHUB_OUTPUT

      - name: Print version
        if: steps.changesets.outputs.published == 'true'
        run: echo "${{ steps.setVersion.outputs.PACKAGE_VERSION }} ......"

      - name: Trigger example repo github action
        if: steps.changesets.outputs.published == 'true'
        run: |
              curl -H "Authorization: Bearer ${{ secrets.MY_GITHUB_TOKEN }}" \
              -H 'Accept: application/vnd.github.everest-preview+json' \
              "https://api.github.com/repos/sanyu1225/turborepo-example/dispatches" \
              -d '{"event_type": "update-package", "client_payload": {"version": "9.8.7"}}'
